import { MindMapTemplate, CustomNode, CustomEdge } from '@/types/mindmap';

const BIOLOGY_KOREAN_NODES: CustomNode[] = [
  { id: 'bio-root', type: 'mindMapNode', position: { x: 0, y: 0 }, data: { label: '고등 생명과학 I 총정리 🧬', emoji: '🧬', colorPreset: 'indigo', fontSize: 'xl', isRoot: true } },
  
  // 가지 1: 세포 생물학 (에메랄드 색상)
  { id: 'bio-b1', type: 'mindMapNode', position: { x: -320, y: -220 }, data: { label: '1. 세포의 구조와 대사 🔬', emoji: '🔬', colorPreset: 'emerald', fontSize: 'lg' } },
  { id: 'bio-b1-1', type: 'mindMapNode', position: { x: -580, y: -300 }, data: { label: '원핵세포 & 진핵세포 구조 비교', colorPreset: 'emerald', fontSize: 'md' } },
  { id: 'bio-b1-2', type: 'mindMapNode', position: { x: -580, y: -220 }, data: { label: '미토콘드리아 (세포 호흡과 ATP 생성을 담당)', colorPreset: 'emerald', fontSize: 'md' } },
  { id: 'bio-b1-3', type: 'mindMapNode', position: { x: -580, y: -140 }, data: { label: '엽록체 (광합성과 유기물 합성)', colorPreset: 'emerald', fontSize: 'md' } },
  { id: 'bio-b1-4', type: 'mindMapNode', position: { x: -840, y: -300 }, data: { label: '세포막의 인지질 이중층 구조', colorPreset: 'emerald', fontSize: 'sm' } },
  { id: 'bio-b1-5', type: 'mindMapNode', position: { x: -840, y: -220 }, data: { label: '능동수송과 능동적 물질 이동', colorPreset: 'emerald', fontSize: 'sm' } },
  { id: 'bio-b1-6', type: 'mindMapNode', position: { x: -840, y: -140 }, data: { label: '리보솜과 단백질 합성 과정', colorPreset: 'emerald', fontSize: 'sm' } },

  // 가지 2: 유전학 & DNA (시안 색상)
  { id: 'bio-b2', type: 'mindMapNode', position: { x: 320, y: -220 }, data: { label: '2. 유전과 염색체 🧬', emoji: '🧬', colorPreset: 'cyan', fontSize: 'lg' } },
  { id: 'bio-b2-1', type: 'mindMapNode', position: { x: 580, y: -300 }, data: { label: 'DNA 이중 나선 구조와 염기쌍', colorPreset: 'cyan', fontSize: 'md' } },
  { id: 'bio-b2-2', type: 'mindMapNode', position: { x: 580, y: -220 }, data: { label: 'RNA 전사와 단백질 번역', colorPreset: 'cyan', fontSize: 'md' } },
  { id: 'bio-b2-3', type: 'mindMapNode', position: { x: 580, y: -140 }, data: { label: '멘델의 유전 법칙 (우열 & 분리 법칙)', colorPreset: 'cyan', fontSize: 'md' } },
  { id: 'bio-b2-4', type: 'mindMapNode', position: { x: 840, y: -300 }, data: { label: '상염색체 vs 성염색체 유전', colorPreset: 'cyan', fontSize: 'sm' } },
  { id: 'bio-b2-5', type: 'mindMapNode', position: { x: 840, y: -220 }, data: { label: '체세포 분열과 감수 분열 비교', colorPreset: 'cyan', fontSize: 'sm' } },
  { id: 'bio-b2-6', type: 'mindMapNode', position: { x: 840, y: -140 }, data: { label: '유전자 돌연변이 및 CRISPR 교정', colorPreset: 'cyan', fontSize: 'sm' } },

  // 가지 3: 인체 생리학 (장미/크림슨 색상)
  { id: 'bio-b3', type: 'mindMapNode', position: { x: -320, y: 220 }, data: { label: '3. 항상성과 기관계 🫀', emoji: '🫀', colorPreset: 'crimson', fontSize: 'lg' } },
  { id: 'bio-b3-1', type: 'mindMapNode', position: { x: -580, y: 140 }, data: { label: '순환계 (심장 구조와 혈관 순환)', colorPreset: 'crimson', fontSize: 'md' } },
  { id: 'bio-b3-2', type: 'mindMapNode', position: { x: -580, y: 220 }, data: { label: '신경계 (자율신경 & 흥분 전달)', colorPreset: 'crimson', fontSize: 'md' } },
  { id: 'bio-b3-3', type: 'mindMapNode', position: { x: -580, y: 300 }, data: { label: '호르몬 조절 (혈당량 & 체온 항상성)', colorPreset: 'crimson', fontSize: 'md' } },
  { id: 'bio-b3-4', type: 'mindMapNode', position: { x: -840, y: 140 }, data: { label: '적혈구와 백혈구의 면역 작용', colorPreset: 'crimson', fontSize: 'sm' } },
  { id: 'bio-b3-5', type: 'mindMapNode', position: { x: -840, y: 220 }, data: { label: '뉴런의 활동 전위와 시냅스 전달', colorPreset: 'crimson', fontSize: 'sm' } },

  // 가지 4: 생태계와 환경 (앰버 색상)
  { id: 'bio-b4', type: 'mindMapNode', position: { x: 320, y: 220 }, data: { label: '4. 생태계와 상호작용 🌿', emoji: '🌿', colorPreset: 'amber', fontSize: 'lg' } },
  { id: 'bio-b4-1', type: 'mindMapNode', position: { x: 580, y: 140 }, data: { label: '자연선택설과 환경 적응', colorPreset: 'amber', fontSize: 'md' } },
  { id: 'bio-b4-2', type: 'mindMapNode', position: { x: 580, y: 220 }, data: { label: '먹이 사슬과 에너지 피라미드', colorPreset: 'amber', fontSize: 'md' } },
  { id: 'bio-b4-3', type: 'mindMapNode', position: { x: 580, y: 300 }, data: { label: '탄소 순환과 질소 순환 과정', colorPreset: 'amber', fontSize: 'md' } },
  { id: 'bio-b4-4', type: 'mindMapNode', position: { x: 840, y: 140 }, data: { label: '종 다양성 보전과 생태계 균형', colorPreset: 'amber', fontSize: 'sm' } },
  { id: 'bio-b4-5', type: 'mindMapNode', position: { x: 840, y: 220 }, data: { label: '기후 변화와 지구 온난화 영향', colorPreset: 'amber', fontSize: 'sm' } },
];

const BIOLOGY_KOREAN_EDGES: CustomEdge[] = [
  { id: 'e-b-root-1', source: 'bio-root', target: 'bio-b1', type: 'smoothstep' },
  { id: 'e-b-1-1', source: 'bio-b1', target: 'bio-b1-1', type: 'smoothstep' },
  { id: 'e-b-1-2', source: 'bio-b1', target: 'bio-b1-2', type: 'smoothstep' },
  { id: 'e-b-1-3', source: 'bio-b1', target: 'bio-b1-3', type: 'smoothstep' },
  { id: 'e-b-1-5', source: 'bio-b1-1', target: 'bio-b1-4', type: 'smoothstep' },
  { id: 'e-b-1-6', source: 'bio-b1-2', target: 'bio-b1-5', type: 'smoothstep' },
  { id: 'e-b-1-7', source: 'bio-b1-3', target: 'bio-b1-6', type: 'smoothstep' },

  { id: 'e-b-root-2', source: 'bio-root', target: 'bio-b2', type: 'smoothstep' },
  { id: 'e-b-2-1', source: 'bio-b2', target: 'bio-b2-1', type: 'smoothstep' },
  { id: 'e-b-2-2', source: 'bio-b2', target: 'bio-b2-2', type: 'smoothstep' },
  { id: 'e-b-2-3', source: 'bio-b2', target: 'bio-b2-3', type: 'smoothstep' },
  { id: 'e-b-2-4', source: 'bio-b2-1', target: 'bio-b2-4', type: 'smoothstep' },
  { id: 'e-b-2-5', source: 'bio-b2-2', target: 'bio-b2-5', type: 'smoothstep' },
  { id: 'e-b-2-6', source: 'bio-b2-3', target: 'bio-b2-6', type: 'smoothstep' },

  { id: 'e-b-root-3', source: 'bio-root', target: 'bio-b3', type: 'smoothstep' },
  { id: 'e-b-3-1', source: 'bio-b3', target: 'bio-b3-1', type: 'smoothstep' },
  { id: 'e-b-3-2', source: 'bio-b3', target: 'bio-b3-2', type: 'smoothstep' },
  { id: 'e-b-3-3', source: 'bio-b3', target: 'bio-b3-3', type: 'smoothstep' },
  { id: 'e-b-3-4', source: 'bio-b3-1', target: 'bio-b3-4', type: 'smoothstep' },
  { id: 'e-b-3-5', source: 'bio-b3-2', target: 'bio-b3-5', type: 'smoothstep' },

  { id: 'e-b-root-4', source: 'bio-root', target: 'bio-b4', type: 'smoothstep' },
  { id: 'e-b-4-1', source: 'bio-b4', target: 'bio-b4-1', type: 'smoothstep' },
  { id: 'e-b-4-2', source: 'bio-b4', target: 'bio-b4-2', type: 'smoothstep' },
  { id: 'e-b-4-3', source: 'bio-b4', target: 'bio-b4-3', type: 'smoothstep' },
  { id: 'e-b-4-4', source: 'bio-b4-1', target: 'bio-b4-4', type: 'smoothstep' },
  { id: 'e-b-4-5', source: 'bio-b4-2', target: 'bio-b4-5', type: 'smoothstep' },
];

export const MINDMAP_TEMPLATES: MindMapTemplate[] = [
  {
    id: 'template-biology-28',
    title: '고등 생명과학 총정리 (25개 노드)',
    description: '세포학, 유전학, 인체 생리학, 생태계를 체계적으로 정리한 마인드맵.',
    category: 'study',
    icon: '🧬',
    nodes: BIOLOGY_KOREAN_NODES,
    edges: BIOLOGY_KOREAN_EDGES,
  },
  {
    id: 'template-exam-plan',
    title: '시험 대비 공부 계획표',
    description: '중간고사/기말고사 과목별 학습 목표 및 복습 일정 정리.',
    category: 'study',
    icon: '🎓',
    nodes: [
      {
        id: 'root',
        type: 'mindMapNode',
        position: { x: 0, y: 0 },
        data: { label: '기말고사 만점 공부 플랜 🎓', emoji: '🎓', colorPreset: 'indigo', fontSize: 'xl', isRoot: true },
      },
      {
        id: 'branch-1',
        type: 'mindMapNode',
        position: { x: -280, y: -150 },
        data: { label: '수학 및 통계학 📐', emoji: '📐', colorPreset: 'emerald', fontSize: 'lg' },
      },
      {
        id: 'b1-child-1',
        type: 'mindMapNode',
        position: { x: -480, y: -220 },
        data: { label: '미적분 기본 정리 및 공식 암기', colorPreset: 'emerald', fontSize: 'md' },
      },
      {
        id: 'b1-child-2',
        type: 'mindMapNode',
        position: { x: -480, y: -110 },
        data: { label: '확률과 통계 기출문제 50제 풀기', colorPreset: 'emerald', fontSize: 'md' },
      },
      {
        id: 'branch-2',
        type: 'mindMapNode',
        position: { x: 280, y: -150 },
        data: { label: '물리학 및 역학 ⚡', emoji: '⚡', colorPreset: 'cyan', fontSize: 'lg' },
      },
      {
        id: 'b2-child-1',
        type: 'mindMapNode',
        position: { x: 480, y: -220 },
        data: { label: '뉴턴의 운동 법칙 사례 분석', colorPreset: 'cyan', fontSize: 'md' },
      },
      {
        id: 'b2-child-2',
        type: 'mindMapNode',
        position: { x: 480, y: -110 },
        data: { label: '전자기학 핵심 공식 노트 만들기', colorPreset: 'cyan', fontSize: 'md' },
      },
      {
        id: 'branch-3',
        type: 'mindMapNode',
        position: { x: -280, y: 150 },
        data: { label: '효율적 시간 관리 ⏰', emoji: '⏰', colorPreset: 'amber', fontSize: 'lg' },
      },
      {
        id: 'b3-child-1',
        type: 'mindMapNode',
        position: { x: -480, y: 110 },
        data: { label: '50분 집중 / 10분 휴식 뽀모도로 루틴', colorPreset: 'amber', fontSize: 'md' },
      },
      {
        id: 'b3-child-2',
        type: 'mindMapNode',
        position: { x: -480, y: 200 },
        data: { label: '인쇄용 암기 카드(Flashcard) 복습', colorPreset: 'amber', fontSize: 'md' },
      },
      {
        id: 'branch-4',
        type: 'mindMapNode',
        position: { x: 280, y: 150 },
        data: { label: '실전 모의고사 풀이 📝', emoji: '📝', colorPreset: 'violet', fontSize: 'lg' },
      },
      {
        id: 'b4-child-1',
        type: 'mindMapNode',
        position: { x: 480, y: 110 },
        data: { label: '2025학년도 6월 모의평가 풀이', colorPreset: 'violet', fontSize: 'md' },
      },
      {
        id: 'b4-child-2',
        type: 'mindMapNode',
        position: { x: 480, y: 200 },
        data: { label: '타이머 설정 후 실전 논술 연습', colorPreset: 'violet', fontSize: 'md' },
      },
    ],
    edges: [
      { id: 'e-root-b1', source: 'root', target: 'branch-1', type: 'smoothstep' },
      { id: 'e-b1-c1', source: 'branch-1', target: 'b1-child-1', type: 'smoothstep' },
      { id: 'e-b1-c2', source: 'branch-1', target: 'b1-child-2', type: 'smoothstep' },
      { id: 'e-root-b2', source: 'root', target: 'branch-2', type: 'smoothstep' },
      { id: 'e-b2-c1', source: 'branch-2', target: 'b2-child-1', type: 'smoothstep' },
      { id: 'e-b2-c2', source: 'branch-2', target: 'b2-child-2', type: 'smoothstep' },
      { id: 'e-root-b3', source: 'root', target: 'branch-3', type: 'smoothstep' },
      { id: 'e-b3-c1', source: 'branch-3', target: 'b3-child-1', type: 'smoothstep' },
      { id: 'e-b3-c2', source: 'branch-3', target: 'b3-child-2', type: 'smoothstep' },
      { id: 'e-root-b4', source: 'root', target: 'branch-4', type: 'smoothstep' },
      { id: 'e-b4-c1', source: 'branch-4', target: 'b4-child-1', type: 'smoothstep' },
      { id: 'e-b4-c2', source: 'branch-4', target: 'b4-child-2', type: 'smoothstep' },
    ],
  },
  {
    id: 'template-book-summary',
    title: '독서 요약 및 문학 분석',
    description: '도서 줄거리, 주제 의식, 인물 관계도 및 주요 명대사 정리.',
    category: 'book',
    icon: '📖',
    nodes: [
      {
        id: 'root',
        type: 'mindMapNode',
        position: { x: 0, y: 0 },
        data: { label: '위대한 개츠비 독서 노트 📖', emoji: '📖', colorPreset: 'amber', fontSize: 'xl', isRoot: true },
      },
      {
        id: 'b1',
        type: 'mindMapNode',
        position: { x: -280, y: -130 },
        data: { label: '핵심 주제 및 사상 🎭', emoji: '🎭', colorPreset: 'crimson', fontSize: 'lg' },
      },
      {
        id: 'b1-1',
        type: 'mindMapNode',
        position: { x: -480, y: -180 },
        data: { label: '아메리칸 드림의 환상과 환멸', colorPreset: 'crimson', fontSize: 'md' },
      },
      {
        id: 'b1-2',
        type: 'mindMapNode',
        position: { x: -480, y: -90 },
        data: { label: '1920년대 미국 계급과 부의 상징', colorPreset: 'crimson', fontSize: 'md' },
      },
      {
        id: 'b2',
        type: 'mindMapNode',
        position: { x: 280, y: -130 },
        data: { label: '등장인물 관계도 👥', emoji: '👥', colorPreset: 'indigo', fontSize: 'lg' },
      },
      {
        id: 'b2-1',
        type: 'mindMapNode',
        position: { x: 480, y: -180 },
        data: { label: '제이 개츠비 (비극적 순정 주인공)', colorPreset: 'indigo', fontSize: 'md' },
      },
      {
        id: 'b2-2',
        type: 'mindMapNode',
        position: { x: 480, y: -90 },
        data: { label: '닉 캐러웨이 (관찰자 및 관찰 서술자)', colorPreset: 'indigo', fontSize: 'md' },
      },
      {
        id: 'b3',
        type: 'mindMapNode',
        position: { x: 0, y: 180 },
        data: { label: '주요 상징과 모티프 ✨', emoji: '✨', colorPreset: 'violet', fontSize: 'lg' },
      },
      {
        id: 'b3-1',
        type: 'mindMapNode',
        position: { x: -220, y: 270 },
        data: { label: '초록색 불빛 (개츠비의 동경과 희망)', colorPreset: 'violet', fontSize: 'md' },
      },
      {
        id: 'b3-2',
        type: 'mindMapNode',
        position: { x: 220, y: 270 },
        data: { label: '재의 계곡 (도덕적 황폐함)', colorPreset: 'violet', fontSize: 'md' },
      },
    ],
    edges: [
      { id: 'e-r-b1', source: 'root', target: 'b1', type: 'smoothstep' },
      { id: 'e-b1-1', source: 'b1', target: 'b1-1', type: 'smoothstep' },
      { id: 'e-b1-2', source: 'b1', target: 'b1-2', type: 'smoothstep' },
      { id: 'e-r-b2', source: 'root', target: 'b2', type: 'smoothstep' },
      { id: 'e-b2-1', source: 'b2', target: 'b2-1', type: 'smoothstep' },
      { id: 'e-b2-2', source: 'b2', target: 'b2-2', type: 'smoothstep' },
      { id: 'e-r-b3', source: 'root', target: 'b3', type: 'smoothstep' },
      { id: 'e-b3-1', source: 'b3', target: 'b3-1', type: 'smoothstep' },
      { id: 'e-b3-2', source: 'b3', target: 'b3-2', type: 'smoothstep' },
    ],
  },
  {
    id: 'template-concept-map',
    title: '인공지능(AI) 개념 지도',
    description: '머신러닝, 딥러닝, 생성형 AI의 분야별 개념 정리 마인드맵.',
    category: 'concept',
    icon: '🤖',
    nodes: [
      {
        id: 'root',
        type: 'mindMapNode',
        position: { x: 0, y: 0 },
        data: { label: '인공지능(AI) 개념 구조 🤖', emoji: '🤖', colorPreset: 'cyan', fontSize: 'xl', isRoot: true },
      },
      {
        id: 'b1',
        type: 'mindMapNode',
        position: { x: -280, y: -130 },
        data: { label: '머신러닝 (Machine Learning) 🧠', emoji: '🧠', colorPreset: 'indigo', fontSize: 'lg' },
      },
      {
        id: 'b1-1',
        type: 'mindMapNode',
        position: { x: -480, y: -190 },
        data: { label: '지도학습 (회귀분석 / 분류 모델)', colorPreset: 'indigo', fontSize: 'md' },
      },
      {
        id: 'b1-2',
        type: 'mindMapNode',
        position: { x: -480, y: -80 },
        data: { label: '비지도학습 (군집화 / K-Means)', colorPreset: 'indigo', fontSize: 'md' },
      },
      {
        id: 'b2',
        type: 'mindMapNode',
        position: { x: 280, y: -130 },
        data: { label: '딥러닝 (Deep Learning) ⚡', emoji: '⚡', colorPreset: 'violet', fontSize: 'lg' },
      },
      {
        id: 'b2-1',
        type: 'mindMapNode',
        position: { x: 480, y: -190 },
        data: { label: '합성곱 신경망 (CNN: 이미지 인식)', colorPreset: 'violet', fontSize: 'md' },
      },
      {
        id: 'b2-2',
        type: 'mindMapNode',
        position: { x: 480, y: -80 },
        data: { label: '트랜스포머 (Transformer & 거대언어모델)', colorPreset: 'violet', fontSize: 'md' },
      },
      {
        id: 'b3',
        type: 'mindMapNode',
        position: { x: 0, y: 160 },
        data: { label: '실생활 활용 분야 🚀', emoji: '🚀', colorPreset: 'emerald', fontSize: 'lg' },
      },
      {
        id: 'b3-1',
        type: 'mindMapNode',
        position: { x: -220, y: 250 },
        data: { label: '자율주행 자동차 및 인공지능 로봇', colorPreset: 'emerald', fontSize: 'md' },
      },
      {
        id: 'b3-2',
        type: 'mindMapNode',
        position: { x: 220, y: 250 },
        data: { label: '의료 영상 진단 및 신약 개발', colorPreset: 'emerald', fontSize: 'md' },
      },
    ],
    edges: [
      { id: 'e-r-b1', source: 'root', target: 'b1', type: 'smoothstep' },
      { id: 'e-b1-1', source: 'b1', target: 'b1-1', type: 'smoothstep' },
      { id: 'e-b1-2', source: 'b1', target: 'b1-2', type: 'smoothstep' },
      { id: 'e-r-b2', source: 'root', target: 'b2', type: 'smoothstep' },
      { id: 'e-b2-1', source: 'b2', target: 'b2-1', type: 'smoothstep' },
      { id: 'e-b2-2', source: 'b2', target: 'b2-2', type: 'smoothstep' },
      { id: 'e-r-b3', source: 'root', target: 'b3', type: 'smoothstep' },
      { id: 'e-b3-1', source: 'b3', target: 'b3-1', type: 'smoothstep' },
      { id: 'e-b3-2', source: 'b3', target: 'b3-2', type: 'smoothstep' },
    ],
  },
];
